package com.insurance.ui.view;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Button;
import com.vaadin.ui.Grid;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ClientListViewDesign extends VerticalLayout {
    protected GridLayout gridLayout;
    protected Label labelFullname;
    protected TextField inpLastname;
    protected TextField inpFirstname;
    protected TextField inpPatronymic;
    protected Button btnSearch;
    protected Grid grid;
    protected Button btnSelect;
    protected Button btnNew;
    protected Button btnClose;

    public ClientListViewDesign() {
        Design.read(this);
    }
}
