package com.insurance.ui.view;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.DateField;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Button;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.Panel;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class EditContractViewDesign extends Panel {
    protected Label labelInsuranceSum;
    protected TextField inpInsuranceSum;
    protected Label labelPeriod;
    protected DateField calPeriodStart;
    protected DateField calPeriodEnd;
    protected Label labelPropertyType;
    protected ComboBox<String> comboPropertyType;
    protected Label labelYearBuilt;
    protected TextField inpYearBuilt;
    protected Label labelSquare;
    protected TextField inpSquare;
    protected Button btnCalculatePremium;
    protected Label labelCalcDate;
    protected DateField calCalcDate;
    protected Label labelPremium;
    protected TextField inpPremium;
    protected Label labelContractNumber;
    protected TextField inpContractNumber;
    protected Label labelDateOfContract;
    protected DateField calContractDate;
    protected Button btnSelectClient;
    protected Label labelFullname;
    protected TextField inpFullname;
    protected Button btnEditClient;
    protected Label labelBirthdate;
    protected DateField calBirthdate;
    protected Label labelPassport;
    protected Label labelPassportSeries;
    protected TextField inpPassportSeries;
    protected Label labelPassportNumber;
    protected TextField inpPassportNumber;
    protected ComboBox<String> comboCountry;
    protected TextField inpPostalCode;
    protected TextField inpRegion;
    protected TextField inpArea;
    protected TextField inpCity;
    protected TextField inpStreet;
    protected TextField inpHouse;
    protected TextField inpHousing;
    protected TextField inpBuilding;
    protected TextField inpApartment;
    protected TextArea inpComment;
    protected Button btnSave;
    protected Button btnCancel;

    public EditContractViewDesign() {
        Design.read(this);
    }
}
