package com.insurance.ui.view;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Button;
import com.vaadin.ui.DateField;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class EditClientViewDesign extends VerticalLayout {
    protected Label labelFullname;
    protected TextField inpLastname;
    protected TextField inpFirstname;
    protected TextField inpPatronymic;
    protected Label labelBirthdate;
    protected DateField calBirthdate;
    protected Label labelPassport;
    protected Label labelPassportSeries;
    protected TextField inpPassportSeries;
    protected Label labelPassportNumber;
    protected TextField inpPassportNumber;
    protected Button btnSave;
    protected Button btnCancel;

    public EditClientViewDesign() {
        Design.read(this);
    }
}
