package com.insurance.ui.view;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Button;
import com.vaadin.ui.DateTimeField;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.DateField;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class EditContractViewDesign extends VerticalLayout {
    protected Label labelInsuranceSum;
    protected TextField inpInsuranceSum;
    protected Label labelPropertyType;
    protected ComboBox<String> comboPropertyType;
    protected Label labelYearBuilt;
    protected TextField inpYearBuilt;
    protected Label labelSquare;
    protected TextField inpSquare;
    protected Button btnCalculatePremium;
    protected Label labelCalcDate;
    protected TextField inpCalcDate;
    protected Label labelPremium;
    protected TextField inpPremium;
    protected Label labelContractNumber;
    protected TextField inpContractNumber;
    protected Label labelDateOfContract;
    protected Label labelPeriod;
    protected DateField calPeriodStart;
    protected DateField calPeriodEnd;
    protected Button btnSelectClient;
    protected Label labelFullname;
    protected TextField inpFullname;
    protected Button btnEditClient;
    protected Label labelBirthdate;
    protected DateTimeField calBirthdate;
    protected Label labelPassport;
    protected Label labelPassportSeries;
    protected TextField inpPassportSeries;
    protected Label labelPassportNumber;
    protected TextField inp;

    public EditContractViewDesign() {
        Design.read(this);
    }
}
